services:
  api:
    build: ./api_server
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    restart: always
  chat:
    build: ./chat_server
    depends_on:
      - mongodb
      - redis
    ports:
      - 8081:8081
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
