apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 31155
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
