apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat
  name: chat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - image: simplechat-chat
          imagePullPolicy: Never
          name: chat-server
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always