apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: chat
  namespace: default
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 31156
  selector:
    app: chat
  type: NodePort
status:
  loadBalancer: {}
